import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'

import './globals.css'

const fontInter = Manrope({
	variable: '--font-geist-sans',
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Omboor',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${fontInter.className} bg-gray-200 antialiased`}
				suppressHydrationWarning
			>
				{children}
			</body>
		</html>
	)
}
