/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UserController_findAll"];
        put?: never;
        /** Create user */
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id */
        get: operations["UserController_findById"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["UserController_delete"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User logged successfully */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User logged out successfully */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User returned successfully */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** User updated successfully */
        patch: operations["AuthController_update"];
        trace?: never;
    };
    "/api/auth/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Password updated successfully */
        patch: operations["AuthController_changePassword"];
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all product */
        get: operations["ProductController_findAll"];
        put?: never;
        /** Create product */
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by name */
        get: operations["ProductController_findByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by id */
        get: operations["ProductController_findById"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["ProductController_delete"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["ProductController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDto: {
            /**
             * @description Уникальный идентификатор пользователя
             * @example c1a2b3d4-e5f6-7890-abcd-1234567890ef
             */
            id: string;
            /**
             * @description Имя пользователя
             * @example Bekzod
             */
            name: string;
            /**
             * @description Фамилия пользователя
             * @example Ravshanbekov
             */
            lastName: string;
            /**
             * @description Ссылка на аватар пользователя
             * @example https://example.com/avatar.png
             */
            avatarUrl?: Record<string, never> | null;
            /**
             * @description Номер телефона пользователя
             * @example +998901234567
             */
            phoneNumber: string;
            /**
             * @description Роль пользователя в системе
             * @example ADMIN
             * @enum {string}
             */
            role: "REGULAR" | "ADMIN";
            /**
             * @description Тарифный план пользователя
             * @example START
             * @enum {string}
             */
            plan: "START" | "ADVANCED" | "PRO";
            /**
             * Format: date-time
             * @description Дата создания пользователя
             * @example 2024-12-01T12:30:00.000Z
             */
            createdAt: string;
        };
        CreateUserRequestDTO: {
            /**
             * @description User name
             * @example Bekzod
             */
            name: string;
            /**
             * @description User last name
             * @example Ravshanbekov
             */
            lastName: string;
            /**
             * @description User password. Must contain uppercase and number
             * @example Password123
             */
            password: string;
            /**
             * @description Repeat password
             * @example Password123
             */
            repeatPassword: string;
            /**
             * @description User phone number
             * @example +1234567890
             */
            phoneNumber: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.png
             */
            avatarUrl?: string;
        };
        UpdateUserRequestDTO: {
            /**
             * @description User name
             * @example Bekzod
             */
            name: string;
            /**
             * @description User last name
             * @example Ravshanbekov
             */
            lastName: string;
            /**
             * @description User password. Must contain uppercase and number
             * @example Password123
             */
            password?: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.png
             */
            avatarUrl?: string;
        };
        LoginRequestDTO: {
            /**
             * @description User phone number
             * @example +1234567890
             */
            phoneNumber: string;
            /**
             * @description User password
             * @example passWord123
             */
            password: string;
        };
        UpdateMeRequestDTO: {
            /**
             * @description User name
             * @example Bekzod
             */
            name: string;
            /**
             * @description User last name
             * @example Ravshanbekov
             */
            lastName: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.png
             */
            avatarUrl?: string;
        };
        ChangePasswordRequestDTO: {
            /**
             * @description User old password. Must contain uppercase and number
             * @example Password123
             */
            oldPassword: string;
            /**
             * @description User password. Must contain uppercase and number
             * @example NewPassword123
             */
            newPassword: string;
            /**
             * @description Repeat password
             * @example NewPassword123
             */
            repeatPassword: string;
        };
        ProductDto: {
            /**
             * @description Уникальный идентификатор товара
             * @example p1234567890abcdef
             */
            id: string;
            /**
             * @description Название товара
             * @example Coca-Cola 1L
             */
            name: string;
            /**
             * @description Описание товара
             * @example Classic coke drink
             */
            description?: Record<string, never> | null;
            /**
             * @description Изображение товара
             * @example https://example.com/product.png
             */
            imgUrl?: Record<string, never> | null;
            /**
             * @description Штрих-код товара
             * @example 4789654123567
             */
            barcode?: Record<string, never> | null;
            /**
             * @description Артикул товара
             * @example CC-001L
             */
            article?: Record<string, never> | null;
            /**
             * @description Бренд товара
             * @example Coca-Cola
             */
            brand?: Record<string, never> | null;
            /**
             * @description Категория товара
             * @example Drinks
             */
            category?: Record<string, never> | null;
            /**
             * @description Тип упаковки
             * @example Bottle
             */
            container?: Record<string, never> | null;
            /**
             * @description Номер или количество единиц упаковки
             * @example 1
             */
            containerNumber?: Record<string, never> | null;
            /**
             * @description Дополнительные опции или свойства товара
             * @example Zero Sugar
             */
            options?: Record<string, never> | null;
            /**
             * @description Количество доступного товара
             * @example 24
             */
            quantity: number;
            /**
             * @description Единица измерения товара
             * @example PCS
             * @enum {string}
             */
            unit: "PCS" | "KG" | "G" | "L" | "ML" | "M" | "CM" | "MM" | "PACK" | "BOX" | "SET";
            /**
             * @description Цена товара
             * @example 12000
             */
            price: number;
            /**
             * @description Размер скидки в процентах
             * @example 10
             */
            discount?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Дата создания товара
             * @example 2024-12-01T12:30:00.000Z
             */
            createdAt: string;
        };
        CreateProductRequestDTO: {
            /**
             * @description Название продукта
             * @example Ковер аниме Наруто
             */
            name: string;
            /**
             * @description Описание продукта
             * @example Ковер с ярким рисунком Наруто. Идеален для детской или игровой зоны. Комфортный и износостойкий материал
             */
            description?: string;
            /**
             * @description Картинка ковра
             * @example https://img.joomcdn.net/237411c7f1cd0cff91a40c0b6913436f846850a2_original.jpeg
             */
            imgUrl?: string;
            /**
             * @description Штрих-код продукта
             * @example 1234567890123
             */
            barcode?: string;
            /**
             * @description Артикул продукта
             * @example ART-00998
             */
            article: string;
            /**
             * @description Бренд продукта
             * @example IKEA
             */
            brand?: string;
            /**
             * @description Категория продукта
             * @example Ковры
             */
            category?: string;
            /**
             * @description Тип контейнера
             * @example Box
             */
            container?: string;
            /**
             * @description Номер контейнера
             * @example 12
             */
            containerNumber?: number;
            /**
             * @description Опции продукта (JSON строка)
             * @example {"size":"large","color":"black"}
             */
            options?: string;
            /**
             * @description Количество товара (необязательно, по умолчанию 0)
             * @example 0
             */
            quantity?: number;
            /**
             * @description Единица измерения
             * @example PCS
             * @enum {string}
             */
            unit: "PCS" | "KG" | "G" | "L" | "ML" | "M" | "CM" | "MM" | "PACK" | "BOX" | "SET";
            /**
             * @description Цена продукта
             * @example 150.5
             */
            price: number;
            /**
             * @description Цена со скидкой
             * @example 120
             */
            discountPrice?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserController_findAll: {
        parameters: {
            query?: {
                /** @description Page number, default 1 */
                page?: string;
                /** @description Items per page, default 10 */
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequestDTO"];
            };
        };
        responses: {
            /** @description User created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User with this phone number is already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequestDTO"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequestDTO"];
            };
        };
        responses: {
            /** @description User created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User with this phone number is already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDTO"];
            };
        };
        responses: {
            /** @description User logged successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Phone number or password is incorrect */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to destroy the session. Please try again later */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User with this ID is not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequestDTO"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User with this ID is not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequestDTO"];
            };
        };
        responses: {
            /** @description Password updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description The old password you provided does not match our records */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User with this ID is not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_findAll: {
        parameters: {
            query?: {
                /** @description Page number, default 1 */
                page?: string;
                /** @description Items per page, default 10 */
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequestDTO"];
            };
        };
        responses: {
            /** @description Product created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductController_findByName: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequestDTO"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
}
